name=ESPNowMasterSubsystem
version=1.0
author=John Martiney
maintainer=John Martiney, Abigail Martiney
sentence=ESP-NOW Master Subsystem Example
paragraph=ESP-NOW Master Subsystem Example Library
category=Subsystem
url=https://github.com/Team-Voltage-386
architectures=esp32
